Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
projectionsStrength = np.array([[np.abs(np.dot(pt, d)) for d in directions] for pt in signal])
bestProjection = np.argmax(projectionsStrength, axis=1)

extracted = [[], [], []]
for b, pt in zip(bestProjection, signal):
    extracted[b].append(pt)

extracted = [np.array(a) for a in splitted] # convert to numpy array
# print(splitted[0].shape, splitted[1].shape, splitted[2].shape)

#display helpers
directionLines = np.array([[-d, d] for d in directions]) # for line display 
color = ['r', 'g', 'b']

for i in range(len(splitted)):
    plt.plot(extracted[i][:, 0],extracted[i][:, 1],"o",markersize=1, c=color[i])
    plt.plot(directionLines[i][:, 0], directionLines[i][:, 1], c=color[i]) # Red straight line
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-13-798bcbd3dc86>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m     [0mextracted[0m[0;34m[[0m[0mb[0m[0;34m][0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mpt[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0mextracted[0m [0;34m=[0m [0;34m[[0m[0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0ma[0m[0;34m)[0m [0;32mfor[0m [0ma[0m [0;32min[0m [0msplitted[0m[0;34m][0m [0;31m# convert to numpy array[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;31m# print(splitted[0].shape, splitted[1].shape, splitted[2].shape)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'splitted' is not defined
NameError: name 'splitted' is not defined

